Publish test results

diff --git a/.github/workflows/plone-package.yml b/.github/workflows/plone-package.yml
--- a/.github/workflows/plone-package.yml
+++ b/.github/workflows/plone-package.yml
@@ -60,6 +60,13 @@ jobs:
         run: buildout -c test_plone${{ matrix.plone-version }}.cfg install test coverage
       - name: Run tests
         run: bin/coverage run bin/test --xml --all
+      - name: Publish test report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Tests
+          path: parts/**/output.xml
+          reporter: jest-junit
 
   pre-commit:
     name: Check pre-commit
